<?php
$showSwitchToUserNameField = json_encode($this->instanceConfig['showSwitchToUserNameField']);
$switchToUserNameLabel = $this->instanceConfig['switchToUserNameLabel'];
$switchBackLabel = $this->instanceConfig['switchBackLabel'];
?>
<div>
    <h1>Switch User</h1>
    <div rcm-switch-user-admin=""
         show-switch-to-user-name-field="<?= $showSwitchToUserNameField ?>"
         switch-to-user-name="''"
         switch-to-user-name-label="'<?= $switchToUserNameLabel ?>'"
         switch-back-label="'<?= $switchBackLabel ?>'"
    >
    </div>
</div>
